[project]
name = "djangoproject-03-09"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.5",
    "django-ckeditor-5>=0.2.18",
    "psycopg2-binary>=2.9.10",
    "redis>=6.4.0",
]
